9 Flexbox
ilyalobatch/Beetroot-Homework pull request #14
Opened 2023-03-16 21:22 UTC by ilyalobatch

2023-03-16 21:24 UTC, ilyalobatch commented
Flexbox Froggy я проходил очень давно полностью
Надеюсь ты мне веришь, раз уж я ребятам намного раньше его кидал)

2023-03-19 08:51 UTC, besvova490 requested changes

2023-03-19 08:51 UTC, besvova490 commented on 9.Flexbox/assets/css/style.css
> +.product-navbar-link::after {
line break is missing before class name

2023-03-19 08:51 UTC, besvova490 commented on 9.Flexbox/index.html
> +            <img class="product-mb-30" src="./assets/imgs/hourglass.svg" alt="hourglass">
add image close tag `<img> => <img/>`

2023-03-19 08:51 UTC, besvova490 commented on 9.Flexbox/index.html
> +            <img class="product-mb-30" src="./assets/imgs/heart.svg" alt="heart">
add image close tag `<img> => <img/>`

2023-03-19 08:51 UTC, besvova490 commented on 9.Flexbox/index.html
> +            <img class="product-mb-30" src="./assets/imgs/design.svg" alt="design">
add image close tag `<img> => <img/>`

2023-03-19 08:51 UTC, besvova490 commented on 9.Flexbox/index.html
> +            <img class="product-mb-30" src="./assets/imgs/cursor.svg" alt="cursor">
add image close tag `<img> => <img/>`

2023-03-19 08:51 UTC, besvova490 commented on 9.Flexbox/index.html
> +        <img src="./assets/imgs/hero-img.jpg" alt="hero-img">
add image close tag ` <img> => <img/>`

2023-03-19 13:10 UTC, besvova490 approved these changes

2023-03-19 13:21 UTC, merged